server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  thymeleaf:
    cache: false
    cache-period: 0
    encoding: UTF-8
    mode: LEGACYHTML5
  template:
    cache: false

ifox-web:
  admin-user-service-base-url: http://localhost:8081/
