server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  thymeleaf:
    cache: false
    cache-period: 0
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates
  template:
    cache: false

ifox-web:
  admin-user-service-base-url: http://localhost:8081/
  file-service-base-url: http://localhost:8085/
  login-url: http://localhost:8080/web/login

#==================== logging Setting =====================#
logging:
  level:
    org.springframework: info
    com.ifox.platform: debug
  file: logs/ifox-web.log
